# Generated by Django 2.1.4 on 2020-02-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bannner',
            new_name='Banner',
        ),
    ]
